### ISSUE TITLE
setOutAlertTo does not work for me

### ISSUE THREAD

**Issue by ptrvg** [KiboOst/php-NetatmoCameraAPI#1]
I can set setOutAlertFrom and it will update on my account.
But when I set setOutAlertTo it won't. There is no error message.

I used the examples from the readme for testing:
//set Presence alert time from 10h15 (always use hh:mm)
$_NAcams->setOutAlertFrom('10:15');

//set Presence alert time to 22h00
$_NAcams->setOutAlertTo('22:00');

When I look in the NetatmoCameraAPI class for the setOutAlertTo it seems to correctly set everything. The only difference between  setOutAlertTo and setOutAlertFrom from is the line:
$setting = 'presence_settings[presence_notify_to]';

**Comment by KiboOst** [comment]
No computer around but I will check that in a few days, sorry for the delay. 
Can you try to set it to '22:01' ? Just a doubt...
Will publish a fix beginning of coming week.

**Comment by ptrvg** [comment]
I checked now with '22:01'. Again it did not work for  setOutAlertTo but it did for setOutAlertFrom

Thanks for looking into this. As a workaround, because I only need this to turn notifications on and off, I set when home to 06.59  -> 07:00 and when away to 07:01 -> 07:00 with  setOutAlertFrom.

**Comment by KiboOst** [comment]
Hi,
Check v1.03 for bug fix.

**Comment by ptrvg** [comment]
It works correct now :)
Thanks for the fast fix.

**Comment by KiboOst** [comment]
Nice ;-)
