### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by glacket** [KiboOst/php-NetatmoCameraAPI#2]
@KiboOst Hi, I am having trouble getting started with this api. I downloaded the api to a folder called /var/netatmoapi then created a php file containing the connection info. I tried starting the connection php file but it just echos back whats in the file. Also I'm not sure what do once its started. how do pull data? do I create another php for that?

**Comment by glacket** [comment]
I messed up and did not format as php file. Now I get the following when trying to connect.

PHP Fatal error:  Call to undefined function curl_init() in /var/netatmoapi/class/NetatmoCameraAPI.php on line 1028

**Comment by KiboOst** [comment]
Hi, yes if you get the php source code it means php isn't interpreted so you have a problem with your php server. 
Undefined function means your php server doesn't have curl extension. It is pretty standard, verify your php version and extensions with phpinfo(). If you don't have curl, install it or activate it.

**Comment by KiboOst** [comment]
Did you managed to run it ?
