### ISSUE TITLE
cURL error: malformed

### ISSUE THREAD

**Issue by bipbipbip** [KiboOst/php-NetatmoCameraAPI#3]
hi 
not working anymore since 3 days…

are they changed something? i have in return : cURL error: malformed

regards

**Comment by KiboOst** [comment]
Strange, all is working fine here. 
Did you changed php version on your server ?

**Comment by bipbipbip** [comment]
not recently, i will look further

**Comment by bipbipbip** [comment]
it seems to be the camera, it appears not connected but send notifications…and can't reconnect it.

**Comment by KiboOst** [comment]
Ok, try shutting it down (un wire it) and plug it back on after a few minutes. If nothing come back contact the support.
